stages:
  data_ingestion:
    cmd: python src/Speaking_Silence/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Speaking_Silence/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data


  prepare_base_model:
    cmd: python src/Speaking_Silence/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Speaking_Silence/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH 
      - SEQUENCE_LENGTH
      - LEARNING_RATE
      - INCLUDE_TOP
      - CLASSES
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/Speaking_Silence/pipeline/stage_03_model_training.py
    deps:
      - src/Speaking_Silence/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/prepare_base_model
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH 
      - SEQUENCE_LENGTH
      - LEARNING_RATE
      - INCLUDE_TOP
      - CLASSES
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5
      - ml_models/model.h5


  evaluation:
    cmd: python src/Speaking_Silence/pipeline/stage_04_model_evaluation.py
    deps:
      - src/Speaking_Silence/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/data
      - artifacts/training/model.h5
      - ml_models/model.h5
    metrics:
    - scores.json:
        cache: false