INCLUDE_TOP: False

SEQUENCE_LENGTH: 50
IMAGE_HEIGHT: 128
IMAGE_WIDTH: 128 

CLASSES: 4
CLASSES_LIST: ["all", "computer", "before", "cool"]

LEARNING_RATE: 0.1
BATCH_SIZE: 16
EPOCHS: 10
AUGMENTATION: True