AUGMENTATION: True
SEQUENCE_LENGTH: 50
IMAGE_HEIGHT: 128
IMAGE_WIDTH: 128 
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 100
CLASSES: 4
CLASSES_LIST: ["all", "computer", "before", "cool"]
LEARNING_RATE: 0.1